version: '3.8'

services:
  ai-market-seg:
    build:
      context: .
      dockerfile: Dockerfile
    image: ai-market-seg:latest
    container_name: ai-market-seg-app
    restart: unless-stopped
    ports:
      - "8080:3000"  # Map container port 3000 to host port 8080
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge
    name: ai-market-seg-network